//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dijshow.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DIJSHOTYPE                  129
#define IDD_SETNUMDLG                   130
#define IDD_SETWEIGHTDLG                131
#define IDC_ENTERNUM                    1000
#define IDC_SETWEIGHT                   1001
#define ID_PATHTOOL                     32771
#define ID_BEGIN                        32772
#define ID_BEGINSEARCH                  32773
#define ID_MOVENODE                     32774
#define ID_EXSTEP                       32775
#define ID_NODETOOL                     32776
#define ID_BUTTON32777                  32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
